SELECT TOP (1000) [id]
      ,[idEvent]
      ,[idEnterprise]
      ,[alert]
      ,[camera]
      ,[duration]
      ,[imageUrl]
      ,[videoUrl]
      ,[eventCoordsX]
      ,[eventCoordsY]
      ,[ip]
      ,[createdAt]
      ,[isActive]
      ,[isError]
      ,[idState]
      ,[attentionAt]
      ,[finishedAt]
      ,[attentionComment]
      ,[finishedComment]
      ,[errorAt]
      ,[errorBy]
      ,[attentionBy]
      ,[imageBaseUrl]
      ,[alertType]
      ,[percent]
      ,[idItem]
      ,[radius]
      ,[idCustomer]
      ,[enterprise]
      ,[customer]
      ,[sendDate]
      ,[idCamera]
  FROM [db-smartechlatam-plataforma].[dbo].[CameraAlertData]
  ORDER BY id DESC;